name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Mise install
        uses: jdx/mise-action@02bfe7363e7097d6516e5814e008d988c4c764e3
        with:
          cache: true
          experimental: true

      - uses: Swatinem/rust-cache@d7ac6f694df60fb8ce48bab7b59ad5da1ac8d46e

      - name: Run build
        run: mise build

      - name: Run tests
        run: mise test
